### ISSUE TITLE
Fails under Linux Mint 20.3

### ISSUE THREAD

**Issue by peterhinch** [AmirHmZz/mpbridge#1]
I attempted to run this under Linux Mint 20.3 with this error message which I've never seen before:
```bash
$ ./main.py
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
```
The system was in a peculiar state with the mouse cursor visible as a cross but not functional. I tried to break in with `ctrl-c` without success. I then tried to close the Bash window, which did break into the program with this traceback:
```bash
^C
^C^X
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
from: can't read /var/mail/typing
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
./main.py: line 8: syntax error near unexpected token `('
./main.py: line 8: `from watchdog.events import ('
```
I had installed the latest version of watchdog.

Running as root had no effect, producing the same symptoms.

**Comment by AmirHmZz** [comment]
I've tested it on Linux Mint 20.3 and solved some bugs with linux filesystem. Which version of python do you use? Could you please try again with latest commit?

**Comment by peterhinch** [comment]
Now I get
```bash
$ ./main.py
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
from: can't read /var/mail/src.session
./main.py: line 7: syntax error near unexpected token `@click.argument'
./main.py: line 7: `@click.argument('port')'
```
My Python version
```bash
$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by AmirHmZz** [comment]
@peterhinch `main.py` is just a python script and is not an executable file yet, so you should try to run this command instead : `python3 main.py <PORT>` and `PORT` must be complete port path (like `/dev/ttyUSB0`). You can also run that command with your user (not `root` user or `sudo` mode) but make sure that your user has access to `PORT`. You can find more information about permitting user to access USB ports [here](https://askubuntu.com/questions/133235/how-do-i-allow-non-root-access-to-ttyusb0).
I will also update `README.md` to make it clear how to use this tool.

**Comment by peterhinch** [comment]
Still no joy. The following session demonstrates that `mpremote.py` is on my path, that the device is on `/dev/ttyACM0`, and that `mpremote` can access it. Also that I have access permission for the port.
```bash
[adminpete@capybara]: ~/micropython-filemanager
$ mpremote.py
Connected to MicroPython at /dev/ttyACM0
Use Ctrl-] to exit this shell

>>> [adminpete@capybara]: ~/micropython-filemanager
$ python3 main.py /dev/ttyACM0
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    start()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 9, in start
    start_session(port)
  File "/home/adminpete/micropython-filemanager/src/session.py", line 70, in start_session
    cp_result = _recursive_copy(dir_path=tmp_dir_path, port=port)
  File "/home/adminpete/micropython-filemanager/src/session.py", line 44, in _recursive_copy
    ls_result = _recursive_ls(
  File "/home/adminpete/micropython-filemanager/src/session.py", line 13, in _recursive_ls
    result = subprocess.run([
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'mpremote'
[adminpete@capybara]: ~/micropython-filemanager
$ 
```

**Comment by AmirHmZz** [comment]
What about `sudo python3 main.py <PORT>`?
It seems `mpremote.py` is known in your shell, but on my devices it's just `mpremote`.
Let me commit some changes in order to detect which one to call on each system.

**Comment by peterhinch** [comment]
```bash
>>> [adminpete@capybara]: ~/micropython-filemanager
$ sudo python3 main.py /dev/ttyACM0
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from src.session import start_session
  File "/home/adminpete/micropython-filemanager/src/session.py", line 6, in <module>
    from watchdog.observers import Observer
ModuleNotFoundError: No module named 'watchdog'
[adminpete@capybara]: ~/micropython-filemanager
$ 
```

**Comment by AmirHmZz** [comment]
Pull the commits, and try :
`sudo python3 -m pip install -r requirements.txt`

**Comment by peterhinch** [comment]
I did this, then had problems with the path using sudo. So I got a root prompt, fixed `$PATH` so that I could run `mpremote.py`, with this outcome:
```python
root@capybara:/home/adminpete/micropython-filemanager# python3 main.py /dev/ttyACM0
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    start()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 9, in start
    start_session(port)
  File "/home/adminpete/micropython-filemanager/src/session.py", line 70, in start_session
    cp_result = _recursive_copy(dir_path=tmp_dir_path, port=port)
  File "/home/adminpete/micropython-filemanager/src/session.py", line 44, in _recursive_copy
    ls_result = _recursive_ls(
  File "/home/adminpete/micropython-filemanager/src/session.py", line 13, in _recursive_ls
    result = subprocess.run([
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'mpremote'
```
I suggest you create a Linux VM or run a Linux live system - you'll get a much quicker turnround than relying on me.

**Comment by AmirHmZz** [comment]
I've done that exactly after you've created this issue and make it work with Linux Mint 20.3. Please try this one:
```
sudo python3 -m pip uninstall mpremote
sudo python3 -m pip install mpremote
```
It's too important to install `mpremote` with sudo to let it add itself to path and also there's no need to add it too `PATH` manually.
After you've re-installed `mpremote` try to do this : `sudo mpremote` and see if it is known by shell or not.

**Comment by peterhinch** [comment]
That now works :) It's a very nice utility.

What has me bamboozled is that it now also works without root privilege. Are you able to explain this? It is possible that I never installed mpremote using `pip`. I helped test `mpremote` when it was still a PR, so set up links and aliases to my local copy. I'll try starting from scratch on another machine and report back.

A possible enhancement might be to provide a means to specify a non-default file manager.

**Comment by peterhinch** [comment]
I've now done the following on another machine and it works:
```bash
$ pip3 install mpremote
$ git clone https://github.com/AmirHmZz/micropython-filemanager
$ sudo python3 -m pip install -r requirements.txt
$ python3 main.py /dev/ttyACM0
```
I don't know if the `sudo` in line 3 was necessary but I've run out of machines with a new enough Python to try without.

So the problem was evidently down to my misconfigured `mpremote`. Apologies. I'll report that it's working in Discussions.

The target I tested on was a Pico with a large number of files. While I use the command line a lot, having the ability to get a graphical display is very useful indeed.

One other thought: a progress indicator that doesn't scroll. My favourite is as below, showing part done:
```
[##########                            ]
```

**Comment by AmirHmZz** [comment]
Thanks :) Please feel free to open issues or PRs to reports bugs or feature requests.

> What has me bamboozled is that it now also works without root privilege. Are you able to explain this? It is possible that I never installed mpremote using pip. I helped test mpremote when it was still a PR, so set up links and aliases to my local copy. 

I guess that the problem was coming from your old `mpremote.py` file's permissions, So your user couldn't execute it because OS was not permitting that to.

> A possible enhancement might be to provide a means to specify a non-default file manager.

After a session starts up, a temporary directory will be created in somewhere and it is accessible to every application/file-manager/etc. So it is enough to open that path in any file explorer you want :D

**Comment by AmirHmZz** [comment]
> So the problem was evidently down to my misconfigured mpremote. Apologies. I'll report that it's working in Discussions.

I owe you an apology because `README.md` was not enough to make things clear. I will update it to make steps more clear than before. I should also thank you for reporting these issues and enlightening possible problems.

> The target I tested on was a Pico with a large number of files. While I use the command line a lot, having the ability to get a graphical display is very useful indeed.

Of course! I will be working on messages soon. Thanks for recommendation.

**Comment by AmirHmZz** [comment]
> A progress indicator that doesn't scroll

Done!

I've also published package on PyPI so there will be no confusion in installation progress anymore.
