### ISSUE TITLE
Add dummy/preview option to sync

### ISSUE THREAD

**Issue by ThinkTransit** [AmirHmZz/mpbridge#23]
It would be really useful to have an option on the sync command that just previews the sync but doesn't actually perform the sync.

Thoughts?

**Comment by Wind-stormger** [comment]
You mean, provide a feature that only checks which files are different or changed and lists them?

Like:
```
git status

git diff
```

**Comment by ThinkTransit** [comment]
Yes exactly, it would be good to preview the sync first. I often run into the issue where my mpbridge ignore file is not correct or doesn't include the correct folders and I need to test it. Sometimes sync can work in the wrong/unexpected direction, overwriting files on the pc.

**Comment by AmirHmZz** [comment]
Seems to be a good idea! Do you think it would be better to have this feature in a completely different command?

**Comment by AmirHmZz** [comment]
Merged in #26 and will be available in `mpbridge v1.3.4`.

**Comment by ThinkTransit** [comment]
Thank you very nice
