### ISSUE TITLE
How to exit the program?

### ISSUE THREAD

**Issue by peterhinch** [AmirHmZz/mpbridge#4]
If you type `ctrl-c` the program quits, but the USB is left in an unusable state. To run tools such as `mpremote` a reboot is required.

**Comment by AmirHmZz** [comment]
I've addressed this issue on [this commit](https://github.com/AmirHmZz/mpbridge/commit/0296e0225e83ed8b8d8ef13744b39bb88ee81fd2). We will keep this issue open until next release to see It is fixed or not.

**Comment by peterhinch** [comment]
That works. As I understand it issuing `exit_raw_repl()` is necessary and correct.

**Comment by AmirHmZz** [comment]
@peterhinch Would you please update to version `0.1.2` and check that problem is solved or not?

**Comment by peterhinch** [comment]
> That works.

That was meant to clarify that I had tested it successfully.

My comment
> As I understand it issuing exit_raw_repl() is necessary and correct.

was in response to your
> We will keep this issue open until next release to see It is fixed or not.

My point is that the `enter_raw_repl` command puts the MicroPython target into a special mode for USB data transfer. You have to issue `exit_raw_repl()` to restore it to normal mode. As I understand it this is intended behaviour rather than an issue to be fixed. Your solution of trapping `ctrl-c` is correct.

I think this issue can be closed.

**Comment by AmirHmZz** [comment]
Thanks again for your help :)
