### ISSUE TITLE
Feature request: support alternative file managers

### ISSUE THREAD

**Issue by peterhinch** [AmirHmZz/mpbridge#5]
When mpbridge is run, the Linux default file manager opens. It would be good if there were a means of specifying an alternative.

If that is impractical, printing the location of the temporary filesystem would provide a hint for those wishing to use an alternative.

**Comment by AmirHmZz** [comment]
`mpbridge` [now](https://github.com/AmirHmZz/mpbridge/releases/tag/0.1.2) prints the temporary path. Which file manager do you prefer? Would you please name it?

**Comment by peterhinch** [comment]
I use Krusader but there are many others. Some users don't use Linux! I was hoping that the file manager could be specified in an optional config file, or as an optional command arg.

This isn't a major issue - mpbridge works fine with Krusader. Printing the path makes it easy for a user to start an alternative file manager.

**Comment by AmirHmZz** [comment]
@peterhinch Do you know how it is possible to open Krusader in a specific directory from terminal?

**Comment by peterhinch** [comment]
```bash
$ krusader /etc
```
(or other path) works but blocks until Krusader exits. I think you could start other file managers similarly.

**Comment by AmirHmZz** [comment]
So we can also implement an option to specify file manager too but it needs to be requested by users one by one to be implemented.

**Comment by peterhinch** [comment]
I now think this is unnecessary. I have fixed this by changing the Linux default file manager. Now `mpbridge` starts with Krusader.
